name: Terraform Destroy

on:
  workflow_dispatch:   # 👈 Manual trigger only

jobs:
  terraform-destroy:
    name: Terraform Destroy
    runs-on: ubuntu-latest

    if: github.ref == 'refs/heads/Ec2_with_ALB_SSL'   # 👈 Only runs on this branch

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.8.3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1  # update if different

    - name: Terraform Init
      run: terraform init

    - name: Terraform Destroy
      run: terraform destroy -auto-approve
